### ISSUE TITLE
关于 shellEndtRva的问题

### ISSUE THREAD

**Issue by yemanqitipo** [YuriSizuku/SimpleDpack#1]
不好意思，我有个疑问。 SimpleDpack.cpp源文件的 第 341行：
DWORD shellEndtRva = m_shellpe.getSectionHeader()[3].VirtualAddress; // rsrc
这里的  m_shellpe.getSectionHeader()[3]并不是 .rsrc节，而是.pdata节，这里是否有问题？

**Comment by YuriSizuku** [comment]
是的，这里不一定是rsrc，代码里是以msvc编译的32位程序为例的。
一般来说.text都在.rsrc前面，这里排除rsrc是为了让图标能正常显示。

**Comment by yemanqitipo** [comment]
您好， SimpleDpack.cpp 源文件第341行：
	m_packpe.getImageDataDirectory()[IMAGE_DIRECTORY_ENTRY_IAT] = {
		m_shellpe.getImageDataDirectory()[IMAGE_DIRECTORY_ENTRY_IMPORT].VirtualAddress + packpeImageSize + offset,
		m_shellpe.getImageDataDirectory()[IMAGE_DIRECTORY_ENTRY_IMPORT].Size};
这里的IAT表被赋予 IMPORT，为什么会这样呢， 这里是否是笔误。
方便加个微信请教一下吗，我的微信号 cfg938706

**Comment by YuriSizuku** [comment]
多谢反馈，这个是笔误写错了。
