### ISSUE TITLE
关于c#加壳问题

### ISSUE THREAD

**Issue by lfy2286238094** [YuriSizuku/SimpleDpack#2]
博主你好，我在学习关于pe方面的逆向工程并参考了您这个加壳的代码，发现c#加壳后打不开，于是乎我用了cff查看了pe结构，由于是新手，所以对这方面了解不多，想问一下c#写的程序和c++写的程序有区别吗，如果想对c#加壳与正常给c++加壳有区别吗？

**Comment by YuriSizuku** [comment]
这个加壳是针对于native code的， 也就是说x86机器码。 c#编译的软件属于是il字节码， 类似于java字节码一类的与硬件无关的中间代码， 所以原理不同、

**Comment by lfy2286238094** [comment]
原来如此，感谢博主的解答，如果我想兼容进来c#或者别的语言程序，我是应该主要修改点在哪一部分呢?    (ps:个人感觉主要是在CSimpleDpack类中的packSection函数，处理区段的问题上，因为我尝试用xdbg时告知我属于无效pe，可能我还需要深入研究研究-.-)
